### ISSUE TITLE
docs: {token} sometimes token

### ISSUE THREAD

**Issue by matthewmueller** [smallwins/slack#10]
Just noticed for: 

```js
slack.users.list({token}, (err, data)=>)  
```
 
is actually:

```js
slack.users.list(token, (err, data)=>)
```

same with `slack.auth.test`, and I suspect a few more.

**Comment by brianleroux** [comment]
ah, no, not anymore, I changed the api in 5.x

**Comment by matthewmueller** [comment]
oh dang aha sorry. must have changed in the last 24 hours :-P

**Comment by brianleroux** [comment]
it did! refactored to generate the web api methods and its just easier taking a state-bag for the first arg always. I'm lazy. :grimacing:
