### ISSUE TITLE
Slack error handling is inconsistent

### ISSUE THREAD

**Issue by oneeman** [smallwins/slack#105]
I recently upgraded from an older version, from back when the library was using request rather than tiny-json-http.  One effect of the upgrade was that the error message we get are now different depending on the status code.  For example, with the older version if you hit rate limiting, the error message would be `ratelimited` (which was in the body of the response from slack).  Now it's `POST failed with: 429`, which is generated by tiny-json-http based on the status code.  On the other hand for errors with a status code of 2xx, since the http request technically suceeded, the library itself generates an error object based on the error in the body.

This strikes me as a change for the worse, compared to how it was in the request library days, because our error handling code now needs to (a) handle some errors based on a text error name and some based on the status code, and (b) deal with the superfluous `POST failed with: ` part.

Anyway, I know the change to tiny-json-http happened a long time ago, and maybe there are a lot of people out there who are now matching on the new error message format or other properties of the error object.  But I thought I'd bring it up as something to think about.

**Comment by brianleroux** [comment]
This is super important and thank you for reporting. 🙏 Agree this is a digression. We moved off request for the payload size but I think Error symmetry is super important. Gonna spend some time thinking about the cleanest solution and will update here.

**Comment by oneeman** [comment]
Good to hear, thanks!  One thing that'd be desirable too, is for whatever solution is chosen to still pass along the response headers (right now they're passed along under `error.raw.headers`, but maybe we don't need the whole raw response and just having them as `e.headers` would be fine).  They're needed specifically for the `ratelimited` error, since slack includes the `retry-after` value as a header rather than in the body.

**Comment by CharlieHess** [comment]
This is another reason I feel like we could allow injecting the post method (#98), to give folks an easy escape hatch. We solved that one with with a custom parameter that's specific to Electron, but if you do that for every case you'll end up with a lot of parameters. 😛

**Comment by brianleroux** [comment]
@oneeman have a look at the commit above and lmk what you think. I decided to add the 'retry-after' header value as a property on the error as `retry` but open to suggestions / ideas. Kinda crummy but this is the only (documented) use of an http status code by Slack so I think we're ok with the 'silly simple' solution. If this is good I'll port to the electron and browser exec fns.

**Comment by oneeman** [comment]
Hi.  I don't know for certain whether this is the only case where the slack API returns an error status code with a message in the body.  Regardless, I would favor making this slightly less specific.

For example, instead of checking for `err && err.message === 'POST failed with: 429'`, I would check for `err && err.body && err.body.message`, and use that as the new error's message if it's not undefined, preserving whatever error message slack may include.

The retry after value would still need special handling such as what you have suggested, though, and that could well be behind another `if` that checks either the error code being 429 or `err.body.message` being `"ratelimited"`

**Comment by oneeman** [comment]
Also, I believe you need to change the following `if` to be `else if`.

**Comment by brianleroux** [comment]
Sorry @oneeman I should've spent more time explaining my reasoning and conclusions here. I agree at a high level with your code review suggestions but digging a bit deeper I think they'll result in a more brittle implementation. 

First of all, we can't know for certain what status codes they use other than what they tell us in their own documentation and communicate via their dev rel. According to their docs rate limiting is the only use of an HTTP status code other than 200. Error conditions in Slack's view of their API is a 200 response with a JSON object that has a bool property `{ok}`. 

https://api.slack.com/docs/rate-limits
https://api.slack.com/web#responses
https://github.com/slackapi/slack-api-specs/blob/master/web-api/slack_web_openapi_v2.json

So while I generally like defensively coding in this particular case I feel it is safer to assume whatever HTTP status codes Slack does eventually decide to support in addition to 200 and 429, if any, it will likely be something we'll want to opt into deliberately. 

Unfortunately `.messsage` will only exist in 'native' javascript `Error` objects. (That property is initialized as the string value passed to an error ctor.) There isn't any reason to think `err.body.message` exists. Their docs do say that 429 returns a JSON object but they do not say what keys are there. We do get `response.body` and `response.headers` but we do not know what either contains. Worse, I tried reproducing a rate limit situation with `slack.api.test` but when it fails I get a 200 response with a body of in `text/html`. 😑

End of the day we can't take responsibility for the Slack API interpretation of HTTP status codes and our client library shouldn't be leaking that stuff anyhow. If there's an error condition we should return a helpful error that, ideally, aligns tightly with the documented behavior. I think while this is a naive implementation it is also the simplest thing that satisfies the original concern. All errors will have the same format and this particular error will have an additional property `.retry` scraped from the headers you can use.

**Comment by brianleroux** [comment]
Good times, I was able to replicate. Looks like only methods that accept a `token` will return this error. I guess that makes sense! 

statusCode: `429` 

body: `{ ok: false, error: 'ratelimited' } `

headers:
```
{ 'content-type': 'application/json; charset=utf-8',
      'content-length': '34',
      connection: 'close',
      'access-control-allow-origin': '*',
      'cache-control': 'private, no-cache, no-store, must-revalidate',
      date: 'Mon, 08 Jan 2018 19:38:49 GMT',
      expires: 'Mon, 26 Jul 1997 05:00:00 GMT',
      pragma: 'no-cache',
      'referrer-policy': 'no-referrer',
      'retry-after': '1',
      server: 'Apache',
      'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
      vary: 'Accept-Encoding',
      'x-content-type-options': 'nosniff',
      'x-oauth-scopes': 'identify,read,post,client,apps,admin',
      'x-slack-backend': 'h',
      'x-slack-req-id': '64b0e921-a5a2-4cd4-a98f-c5aadf995a10',
      'x-xss-protection': '0',
      'x-cache': 'Error from cloudfront',
      via: '1.1 73b5e08c6138e8537ea4c8edfef5e6df.cloudfront.net (CloudFront)',
      'x-amz-cf-id': 'EpFmv7GFJzABZET7Pxj9bsQK7I8R4lBhR5x4GWl7g1xe6xh9LhKaZQ==' }
```

**Comment by brianleroux** [comment]
Ok, gonna publish this as `10.0.0`! The only breaking change being the error.message change. Let me know in a fresh issue if this causing any new problems. Thx for reporting and helping me work through the solution!
