### ISSUE TITLE
Unable to send slack.chat.postMessage with JSON format

### ISSUE THREAD

**Issue by OllyNuralAND** [smallwins/slack#111]
Hi,

I'm new to this, so apologies if this is incorrectly formatted or needs some work as a request.

When sending a postMessage, I am trying to pass in a JSON message so as to display to the user, and when received on slack my message is always appearing as a string - and not being parsed as JSON and displaying a nice format. (See [here](https://api.slack.com/docs/messages/builder?msg=%7B%22attachments%22%3A%5B%7B%22fallback%22%3A%22Required%20plain-text%20summary%20of%20the%20attachment.%22%2C%22color%22%3A%22%2336a64f%22%2C%22pretext%22%3A%22Optional%20text%20that%20appears%20above%20the%20attachment%20block%22%2C%22author_name%22%3A%22Bobby%20Tables%22%2C%22author_link%22%3A%22http%3A%2F%2Fflickr.com%2Fbobby%2F%22%2C%22author_icon%22%3A%22http%3A%2F%2Fflickr.com%2Ficons%2Fbobby.jpg%22%2C%22title%22%3A%22Slack%20API%20Documentation%22%2C%22title_link%22%3A%22https%3A%2F%2Fapi.slack.com%2F%22%2C%22text%22%3A%22Optional%20text%20that%20appears%20within%20the%20attachment%22%2C%22fields%22%3A%5B%7B%22title%22%3A%22Priority%22%2C%22value%22%3A%22High%22%2C%22short%22%3Afalse%7D%5D%2C%22image_url%22%3A%22http%3A%2F%2Fmy-website.com%2Fpath%2Fto%2Fimage.jpg%22%2C%22thumb_url%22%3A%22http%3A%2F%2Fexample.com%2Fpath%2Fto%2Fthumb.png%22%2C%22footer%22%3A%22Slack%20API%22%2C%22footer_icon%22%3A%22https%3A%2F%2Fplatform.slack-edge.com%2Fimg%2Fdefault_application_icon.png%22%2C%22ts%22%3A123456789%7D%5D%7D))

Running on v10.1.1 on OSX

**Example code:**

```
const Slack = require('slack')
const slack = new Slack({token: config.slackAuthenticationConfig.token})

let reposToSend = {
  attachments : [
    {
      title: repo.full_name,
      title_link: repo.html_url,
      color: "#0000FF",
      text: "Last pushed to on: " + repo.pushed_at
  },
  ...
  ]
}

slack.chat.postMessage({
    text: JSON.stringify(reposToSend), 
    attachments: reposToSend, 
    channel: config.slackConfig.channel, 
    username: 'Some Github bot'
})
```

**Expected** - something similar to link above whereby a nicely formatted message is shown

**Actual** - In slack seeing this:

"{"attachments":[{"title":"some title","title_link":"some title link","color":"#0000FF","text":"some text"},...]}"

I have had a look through the code, and perhaps am thinking it is because it are not setting the 'Content-Type' : 'application/json' anywhere? The same request works when using webhooks, but it seems the capability was added for this format in October 2017.

Thanks!

**Comment by danprince** [comment]
Hey @OllyNuralAND! You shouldn't need to stringify anything yourself (unless you want it to show up as JSON in Slack).

The `text` property sets the raw text you want to show up in Slack. The content in `reposToSend` can be passed directly to `chat.postMessage`.

```js
slack.chat.postMessage({
  text: "...",
  attachments: [{
    title: repo.full_name,
    title_link: repo.html_url,
    color: "#0000FF",
    text: "Last pushed to on: " + repo.pushed_at
  }],
  channel: config.slackConfig.channel, 
  username: 'Some Github bot'
})
```

Let me know if that helps you out!

**Comment by OllyNuralAND** [comment]
Hey :) I completely forgot to mention, I had tried that - as in same as above but with JSON.stringify(reposToSend), however to no avail. I still receive the same string JSON in Slack.

Also my code example above is a bit off, ```attachments``` does not apply or affect my requests in any way. Looking at the API, it doesn't even seem to be a param I can use! I only tried it because of the actual slack API.

**Comment by danprince** [comment]
I think you're still getting a JSON string in Slack, because you're using `JSON.stringify` when you don't need to be.

If you want to keep `reposToSend` as a separate object, then you'd need to merge it into the parameters you're already specifying.

```js
slack.chat.postMessage({
  text: "Whatever you want this to say",
  attachments: reposToSend.attachments,
  channel: config.slackConfig.channel, 
  username: 'Some Github bot'
})
```

Could you try that exact code and post a screenshot of how that shows up in Slack for you?

**Comment by danprince** [comment]
If you're interested, the code which sets the `Content-type` and handles the `JSON.stringify` for you is all in [tiny-json-http](https://github.com/brianleroux/tiny-json-http).

**Comment by OllyNuralAND** [comment]
Ahhhhh it was the reposToSend.attachments that was getting me, my bad. 

Thanks for your super quick help! Very glad I get to use this than having to handle requests myself :)

**Comment by danprince** [comment]
No problem! Sometimes all it needs is a second pair of eyes!
