### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by danthegoodman** [smallwins/slack#112]
Hi! Love the project. Thank you for writing and maintaining it!

I've been using it for a while, and just noticed I'm several major versions behind. I'm at v8 but v10 is the latest.

I don't see a changelog for the project, and the github releases don't provide any information either. I glanced through the commit history but wasn't very successful in gathering important informational pieces.

Sorry to be a bother, but can you create a minor changelog, at least highlighting what some of the differences are between major versions? If not, can you describe some of them? I can create a PR from that information if you'd like.

**Comment by brianleroux** [comment]
Hey sorry this wasn't easy and obvious stuff to find! That's annoying. Good news is the changeset is easy to describe. The API is fully backwards compatible to 1.0 and we've added a number of things! ✨ 

(Some error conditions are now returning slightly different payloads and we removed A LOT of dependencies along the way so we bumped the semver major in those cases. ) 

More detail in these two blog posts:

- https://blog.begin.com/introducing-slack-js-9-0-0-c425a63cc479
- https://blog.begin.com/slack-for-js-10-x-428922101703

LMK if that helps (or not) and I can fill in more blanks here.

**Comment by danthegoodman** [comment]
Ah! I see now that you mention the backwards compat to v1.0 in your Readme. Thank you for the blog post links! Those help a lot!

**Comment by j0k3r** [comment]
Even if blog post are cool to try to understand what changed, it should be considered a good practice to create a tag / release on GitHub when you release a new version on NPM. So, even if you don't provide a changelog, we can compare what changed between each version 🙂

**Comment by brianleroux** [comment]
Great feedback and super true thx @j0k3r ! Also remember PR's very welcome.
