### ISSUE TITLE
Proxy handling

### ISSUE THREAD

**Issue by edenlu** [smallwins/slack#114]
For the npm module "request"
it handles proxy by respecting the following : 
HTTP_PROXY / http_proxy
HTTPS_PROXY / https_proxy
NO_PROXY / no_proxy

By setting these environment variables, the module is able to set up the proxy configuration
Then we can connect to slack when behind a proxy

example
```
process.env.HTTP_PROXY = "http://proxy.van.some.proxy:8080";
process.env.HTTPS_PROXY = "http://proxy.van.some.proxy:8080";
var slackToken = "my slack robot token";

//Then this will send a test request to slack and able to come back with a response
let response = request.post({
    url: 'https://slack.com/api/api.test',
    formData: {
        token: slackToken
    }
}, function (err, response) {
    if (err || response.statusCode !== 200) {
        console.log(JSON.parse(err));
        reject("request error");
    } else {
        resolve(JSON.parse(response.body));
    }
})
```

However, this approach seems doesn't work on the "slack" module
```
process.env.HTTP_PROXY = "http://proxy.van.some.proxy:8080";
process.env.HTTPS_PROXY = "http://proxy.van.some.proxy:8080";
var slackToken = "my slack robot token";

//This get hang
let response = slack.api.test({
    token: slackToken
}).then(console.log).catch(console.log);
```

Is there a way to send a request to slack API using this module when behind a proxy?

**Comment by danprince** [comment]
![](https://media2.giphy.com/media/tu54GM19sqJOw/giphy.gif)

**Comment by danprince** [comment]
Happy to help you out! But I'm not entirely sure what you're getting at...

**Comment by edenlu** [comment]
@danprince I recently updated the completed issue, can you check it out again? Thanks for the engaging!

**Comment by danprince** [comment]
This is something that would need to go into https://www.npmjs.com/package/tiny-json-http rather than this package, but based on [how it works in request](https://github.com/request/request/blob/5ba8eb44da7cd639ca21070ea9be20d611b85f66/request.js#L392-L400) it doesn't look like it would be too much work.

**Comment by brianleroux** [comment]
Ah! yes, that makes good sense. (Thx for opening on the tiny-json-http repo Dan.) I will try to look at this shortly!

**Comment by brianleroux** [comment]
Just bumping this thread; I still like the idea but do not have the cycles to implement. If anyone wants to send a PR that'd be sweet. Going to close for now but feel free to reopen if you want to keep the viability up.
