### ISSUE TITLE
Listen for messages using the RTM

### ISSUE THREAD

**Issue by gazpachu** [smallwins/slack#119]
What's the correct way to listen for messages in a slack channel using the RTM API? https://api.slack.com/events/message

In v8.1.1, I used to do this:

```
this.bot.message((payload) => {});

this.bot.user_typing((data) => {});
```

But that doesn't seem to work anymore in the latest version.

I've checked inside the slack object and inside `rtm` I can only find two methods: `connect` and `start`

**Comment by brianleroux** [comment]
Ah sorry we deprecated that API in 9.x but you can still find the code here https://github.com/smallwins/slack/blob/0ab67869ab671664f8a299f74dd4e9f5d2472334/src/rtm.client.js

**Comment by gazpachu** [comment]
@brianleroux thanks. May I know why the RTM API was deprecated in the lib?  How would users be able to fetch messages without having to ping the slack api every x seconds?

**Comment by danprince** [comment]
@gazpachu I think the [Events API](https://api.slack.com/events-api) is probably what you want. Create a webhook for Slack to call, then subscribe to the [Event Types](https://api.slack.com/events/api) you need (probably the `message` family).

**Comment by brianleroux** [comment]
yep! it is way better because you don't need to keep a socket open. just need a web-accessible url for slack to ping as the events happen. works great!
