### ISSUE TITLE
How to I get the install jenkins app details?

### ISSUE THREAD

**Issue by vpriya95** [smallwins/slack#120]
As a Developer,I need to send the notification to the user's Slack Channel (That channel has Jenkins CI app) from Jenkins dynamically.

So I have to get the below things of Jenkins CI app(Already installed in user's channel)by using Slack OAuth.

1.Team Subdomain 
2.Integration Token
3.Base URL
I got the access token by using Slack API Documentation. But I don't have the clue to get those things by using access token in API Call. Can anyone help me out please?

**Comment by ryanblock** [comment]
Hey there! I think you may be in the wrong place?

Please check out:
- https://slack.com/apps/A0F7VRFKN-jenkins-ci
- https://wiki.jenkins.io/display/JENKINS/Slack+Plugin
