### ISSUE TITLE
Not running in webpack target electron-renderer

### ISSUE THREAD

**Issue by natew** [smallwins/slack#125]
The package `http` is seen as missing.

Wondering, how does it even work normally? Browserify somehow polyfills for http?

![image](https://user-images.githubusercontent.com/12100/43732843-925de71a-9967-11e8-8125-999556d5403f.png)

**Comment by brianleroux** [comment]
yeah it does; idk how webpack users do this normally but would appreciate any guidance in how you'd like it to work. maybe we can provide a webpack example. (it used to work fwiw)

**Comment by adam2645** [comment]
I found a fix by going into src/_exec.js and change http variable to the required module to 'http' instead of 'tiny-json-http'.

`var http = require('tiny-json-http')`

`var http = require('http')`

If you run webpack, this error should be gone.

**Comment by brianleroux** [comment]
@adam2645 pls send a PR!

**Comment by adam2645** [comment]
#134

**Comment by adam2645** [comment]
@brianleroux #134

**Comment by brianleroux** [comment]
merged and publishing later today!
