### ISSUE TITLE
promise return twice

### ISSUE THREAD

**Issue by Workaja** [smallwins/slack#129]
hello..

i just thought this one, when testing the this repo on my reactjs project. I am using conversation.history() to call the history of a channel on my slack.

it return 100 message on single return, but it send me another same response.

so I got two responses that I think its identical / same, is this a bug or teach me to get only single return even it give me same data twice... (I mean, what I must do with this if its not a bug)

thanks, sorry for bad grammar

**Comment by Workaja** [comment]
sorry my bad, it called twice on component

**Comment by brianleroux** [comment]
Np! Happens :)

**Comment by Workaja** [comment]
btw, after I try this code on my page component:

let slek = new Slack({token})
slek.conversations.history({channel}, console.log)

it same, return data twice like the screen shot
![image](https://user-images.githubusercontent.com/40653902/56784598-70f4ae00-681b-11e9-874d-622df84bbadc.png)

it is normal ?
if yes, how I can get the return once ?
