### ISSUE TITLE
prepublish script makes it harder to use a fork

### ISSUE THREAD

**Issue by matthewmueller** [smallwins/slack#13]
Not sure you'll want to address this, but right now it's hard to use a fork because the source gets build on `npm publish`. Not a huge deal, just sort of annoying to publish slack-2 haha.

**Comment by brianleroux** [comment]
def open to changing things / there has been a surprising amount of pushback on es6 (added you as a collaborator on Github and owner for the module on Slack btw!)

**Comment by matthewmueller** [comment]
Awesome, thanks!

Personally, I think with having it be ES6 the code is more aesthetically pleasing, but currently harder to hack on. Startup time for babel-node is too slow right now and forks and whatnot break. I like that it will save kilobytes in the browser even though I haven't used it on the client-side just yet.

Anddd, since I'm on a roll here, I'd also like to add a faux Slack server that you can run tests against. I have something locally that I'm thinking of pushing up if there's no objections.

**Comment by brianleroux** [comment]
- agree the es6 code is easier to read
- startup time on node-babel nbd for apps using this as a module (b/c we publish as es5)…do you mean for hacking local w/ the repl?
- local tests would rock: add as a branch (or PR) for me to check out!

**Comment by matthewmueller** [comment]
> startup time on node-babel nbd for apps using this as a module (b/c we publish as es5)…do you mean for hacking local w/ the repl?

yah, for hacking locally :-)

> local tests would rock: add as a branch (or PR) for me to check out!

cool sounds good. i should get to this soon, but no promises ;-)
