### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by codan84** [smallwins/slack#136]
I am trying to run this in AWS Lambda (Node 10), packaged using the following webpack config:
```
const path = require('path')
const slsw = require('serverless-webpack')

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  mode: 'development',
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: ['babel-loader']
      }
    ]
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js'
  }
}
```

I use the library in the following way:
```
import slack from 'slack'

const getUserEmail = userId => {
 const userRequestParams = {
    token: 'xoxb-.......',
    user: userId
  }
  return slack.users.info(userRequestParams)
}
```
For some reason testing this code locally in Node repl works, but once webpacked and running in AWS Lambda I am getting this error:
```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'http'",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'http'",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
        "    at startup (internal/bootstrap/node.js:283:19)"
    ]
}
```

**Comment by Jwalin-Thaker** [comment]
Encountering the same issue!

**Comment by ryanblock** [comment]
Totally willing to be wrong, but I feel like this issue is a request to debug Webpack behavior. `slack` is a CommonJS module, it doesn't really "support" Webpack or any other bundler any more than any module can or does. Can you point to any specific code or concern that is unique to `slack`?

Related, a quick google search turned this up, maybe this could help: https://github.com/browserify/http-browserify

Please do reopen if we can pinpoint a `slack`-specific bug!

**Comment by Lunnatica** [comment]
Having the same problem!

**Comment by ryanblock** [comment]
Cool, sounds like you didn't read the message above, but always happy to review a PR.

**Comment by Lunnatica** [comment]
Don't worry - I switched to the official Slack one and that worked.

For the people who come searching for an answer, this library works fine: https://github.com/slackapi/node-slack-sdk
