### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by Coolranch** [smallwins/slack#206]
When creating a new app using npx create-react-app and using the latest slack version (^11.0.2) I get the following error below.  I am currently running node v16.13.2.

Compiled with problems:

ERROR in ./node_modules/slack/src/_exec-electron.js 1:9-31

Module not found: Error: Can't resolve 'querystring' in 'C:\projects\daily-checkin\node_modules\slack\src'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "querystring": require.resolve("querystring-es3") }'
	- install 'querystring-es3'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "querystring": false }

ERROR in ./node_modules/slack/src/_exec-electron.js 3:10-24

Module not found: Error: Can't resolve 'url' in 'C:\projects\daily-checkin\node_modules\slack\src'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
	- install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "url": false }

**Comment by ryanblock** [comment]
It's hard to tell here what is quoted code and what is your commentary, there are no repro steps, and this appears to be a webpack issue, so I'm not really sure what we can do for you here?

**Comment by ryanblock** [comment]
Ok well let us know if you have anything else here we can work with.
