### ISSUE TITLE
Debugger statement seems to kill process when `bot.started` handler does something sync

### ISSUE THREAD

**Issue by jimkang** [smallwins/slack#23]
I don't know if this is necessarily a problem in this module, but I ran across this weirdness this morning and was wondering if you have any insight into this. To see the problem:

1. Create a file named `test-debug-crash.js` with this in it:

        var slack = require('slack');
        var bot = slack.rtm.client();
        var token = 'your bot token';
        
        var userId;
        var username;

        // do something with the rtm.start payload
        bot.started(function(payload) {
          console.log('payload from rtm.start', payload);
        });

        // respond to a message message
        bot.message(function(msg) {
          debugger;
        });

        // start listening to the slack team associated to the token
        bot.listen({token:token})

2. Run it with Node 5.2.0 via `node debug test-debug-crash.js`.

3. Go over to a Slack channel that has your bot in it and type 'a' (or anything).

The process terminates without any error messages. However, if you take out the console.log, the debugger will correctly break in the message callback. If you remove the debugger statement and put back the console.log, it will not crash when a message comes in.

**Comment by brianleroux** [comment]
can't reproduce in 6.x or 4.x … is this ok to close or would you like me to dig in more?

**Comment by jimkang** [comment]
Yup, fine to close! Thanks for checking.
