### ISSUE TITLE
NPM build is missing new rtm events, as well as dnd namespaced functions.

### ISSUE THREAD

**Issue by loklaan** [smallwins/slack#28]
Hey there,

I've noticed that the `dnd` namespace isn't in the npm build package, although it can be found in a local build of the project.

Also, there have been a couple new rtm events added to the Slack API. I've tested the rtm events generator script, and they are included in the output just fine.

So, to summarise:

* package needs it's generator scripts run to update rtm events
* take care to notice if the `dnd` namespace gets included in the build for npm, before next publishing

Thanks for making this module. The DX is also very nice. :+1:

**Comment by brianleroux** [comment]
heyo! sorry just seeing this tonight / will look at pushing a fresh build out tmrw! thx!

**Comment by loklaan** [comment]
No worries mate.

**Comment by brianleroux** [comment]
Build is up and the DnD stuff is there. Just lookin at adding reminders. LMK if you run into anything else!
