### ISSUE TITLE
A small topic about how to scale it would be very nice!

### ISSUE THREAD

**Issue by thelinuxlich** [smallwins/slack#30]

**Comment by brianleroux** [comment]
hi @thelinuxlich ! could you give me a bit more detail about what you mean by 'how to scale'?

**Comment by brianleroux** [comment]
ping!

**Comment by thelinuxlich** [comment]
Ooops, sorry for the delay. I want to write a Bot-as-a-service for many teams, and would like to scale by adding cheap 1-core instances as needed for those RTM connections.

**Comment by brianleroux** [comment]
Something like this might be interesting to you: https://beepboophq.com/

Effectively the pattern you describe is what we're doing. One container per socket. There are rumors this approach won't be needed for Slack soon with webhooks soon.

**Comment by brianleroux** [comment]
(Feel free to shoot me an email if you wanna chat more about this: b at brian dot io)
