### ISSUE TITLE
Missing users.identify web API method

### ISSUE THREAD

**Issue by tkmcc** [smallwins/slack#32]
Hello,

There is a new Slack web API method, [users.identify](https://api.slack.com/methods/users.identity), that is required to support the new [Sign in with Slack auth flow](https://api.slack.com/docs/sign-in-with-slack).

I have submitted pull request #31 to add this functionality. Please let me know if I missed anything.

Thank you,
Thomas

**Comment by brianleroux** [comment]
:thum
