### ISSUE TITLE
Running in a container - what port needs to be mapped to listen?

### ISSUE THREAD

**Issue by jwulf** [smallwins/slack#38]
I've got it working on my dev machine, but when I run my app in a docker container, it can speak but not listen.

I'm assuming that to hear messages, the RTM API needs to listen on a port? Which port do I need to map to the host?

**Comment by brianleroux** [comment]
No port needed! Slack sends a payload to `rtm.start` with all the info the connection needs. 

Here's a working snippet:

```javascript
var slack = require('slack')
var bot = slack.rtm.client()
var token = process.env.SLACK_TOKEN

bot.hello(function hello(message) {
  console.log(`Got a message: ${message}`)
  bot.close()
})

bot.listen({token:token})
```
Sorry for the delayed response! Let me know if this doesn't answer your q. Happy to help further.
