### ISSUE TITLE
Cannot npm install on windows

### ISSUE THREAD

**Issue by togakangaroo** [smallwins/slack#39]
! Failed at the slack@7.5.6 build script 'babel src --out-dir methods && cp src/api.json methods/api.json'

cp, while a command in powershell is *not* one in cmd, which is the default for shell scripts

**Comment by brianleroux** [comment]
Whoops! Thx for reporting @togakangaroo 👊 

I just pushed up a patch `slack@7.5.7` can you let me know if that fixes the issue? (I don't have a windows machine or image handy where I'm at rn.)

**Comment by togakangaroo** [comment]
All good now @brianleroux

**Comment by brianleroux** [comment]
🆒 Thx again for letting us know!
