### ISSUE TITLE
files.files.comments method path

### ISSUE THREAD

**Issue by leviwheatcroft** [smallwins/slack#44]
[This object](https://github.com/smallwins/slack/blob/master/src/files.js#L12) should be:

```
export default {
  delete: del,
  info,
  list,
  upload,
  comments: {
    add: filesCommentsAdd,
    delete: filesCommentsDelete,
    edit: filesCommentsEdit
  },
  revokePublicURL,
  sharedPublicURL
}
```

In it's current form the api property for `filesCommentsAdd` is `slack.files.files.comments.add`

**Comment by brianleroux** [comment]
oh! good catch. on it!

**Comment by brianleroux** [comment]
(Will post patched to npm shortly)

**Comment by leviwheatcroft** [comment]
quickest patch ever.. love your work mate.

**Comment by brianleroux** [comment]
🙇Thx!!
