### ISSUE TITLE
Refusing to install slack as a dependency of itself

### ISSUE THREAD

**Issue by patrickml** [smallwins/slack#45]
Im trying to install this npm module and keep getting this error `Refusing to install slack as a dependency of itself`

**Comment by brianleroux** [comment]
Hmmmm, sounds like you might be running `npm i slack` in a repo with a package.json with a name property `slack`?

**Comment by patrickml** [comment]
Ah, I didn't even think about that. You are correct. Thank you.

**Comment by patrickml** [comment]
Ah you are correct, I didn't even think about that. Thank you!

**Comment by brianleroux** [comment]
👍💯💟🎊
