### ISSUE TITLE
Generated api.client.js is invalid. Reference crash.

### ISSUE THREAD

**Issue by alexeygt** [smallwins/slack#48]
It seems this code was generated with an error:

`applied.files.comments = {}`
`applied.files = {}`

It renders client API unusable in latest published version.

**Comment by brianleroux** [comment]
Wow, sorry about this @alexeygt / tests are passing so I'm just looking to reproduce now!

**Comment by brianleroux** [comment]
@alexeygt can you give me detailed steps to reproduce the issue you are seeing?

**Comment by alexeygt** [comment]
It's trivial:

`var slack = require('slack');`
`var client = slack.api.client('xxxxxxxxxxxx');`

Looks like your tests do not cover stateful client API. I suspect (not sure though) that core problem is in **src/api.json** that is used to generate all method wrappers. For some reason in has "files.comments.*" methods defined before "files.*" methods.

**Comment by brianleroux** [comment]
oof! 😹 super sorry about that. fixed in `8.1.0` on npm! (and added tests so that does not happen again 💯)
