### ISSUE TITLE
looking for example on how to post to a channel

### ISSUE THREAD

**Issue by ORESoftware** [smallwins/slack#53]
Looking for documentation/example on how to do this:

1. I have a Slack organization called sumanjs (sumanjs.slack.com)
2. I have a channel in this org called "global-command-history".
3. I want to post messages to this channel.

This seems like the most common use case (or one of the most common) and I am struggling to figure out how to do this with your library.  

I looked in the repo to see if there was an examples dir, and I didn't see anything. The readme.md seems to be the full docs and it's pretty good, but I am honestly struggling a bit to get my head around your library's API.

Any help would be appreciated!

**Comment by ORESoftware** [comment]
Looking at the slack-node project, it seems like the way to do the above is with this lib:

```js
slack.chat.postMessage({token, channel, text}, (err, data)=> {});
```

this is a little counterintuitive, and I feel like I am just guessing. I would have originally guessed that to post a message to a channel would be with slack.channel.postMessage.

and example in the docs on how to do this would be so great!

**Comment by brianleroux** [comment]
The API for this library  is a direct mapping to Slacks own Web API. (Their docs are super good!) https://api.slack.com/methods

In the case of posting a message the API is (as you found) 

```javascript
var slack = require('slack')

slack.chat.postMessage({token, channel, text}, console.log)
```

 Per 
https://api.slack.com/methods/chat.postMessage

HTH!

**Comment by ORESoftware** [comment]
ahh thanks, duh, the slack docs should work, thanks

**Comment by brianleroux** [comment]
Np: happy to help. Lmk if you have more questions as you go. Always looking to improve the library too so this case indicated to me we should have a really simple QuickStart example. 👍

**Comment by ORESoftware** [comment]
yeah I can write a bit of that if you want because I just did this

**Comment by brianleroux** [comment]
That would be awesome 🌟
