### ISSUE TITLE
possible bug - slack.channels.history

### ISSUE THREAD

**Issue by ORESoftware** [smallwins/slack#54]
This might not be a bug, and if it is a bug, it's probably a Slack API bug and not a bug in this lib, but maybe you can tell me if I am wrong:

this works

```js
  slack.chat.postMessage({

    token: process.env.SLACK_TOKEN,
    channel: '#suman-all-commands',
    text: JSON.stringify({
      command: process.argv,
      config: global.sumanConfig
    })

  }, (err, data) => {
    if (err) {
      console.error(err.stack || err);
    }
    else {
      console.log('data => ', data);
    }
  });
```

but this gives me an error: 

```js
slack.channels.history({

    token: token,
    channel: '#suman-all-commands'

}, (err, data) => {

    if (err) {
        console.log(err.stack || err);
    }
    else {
        console.log(data);
    }

});
```

the error from the second script is:

```
Error: channel_not_found
    at _res (/home/oleg/.suman/node_modules/slack/methods/_exec.js:40:16)
    at IncomingMessage.<anonymous> (/home/oleg/.suman/node_modules/tiny-json-http/_post.js:47:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

How annoying is that?! :)

Same channel name, same token, and I confirmed the channel is public not private.

Any idea what it could be? Let me know if I should report it to Slack, thanks for your time.

**Comment by brianleroux** [comment]
Ah, ya this can be confusing. Looks like `channel.history` wants a channel id not a name per https://api.slack.com/methods/channels.history

**Comment by ORESoftware** [comment]
ok, maybe the Slack API could be improved, but if you could ask for channel_id instead of channel that would be better I think right? (Don't make it a breaking change, accept either {channel or channel_id}, but the docs should say channel_id not channel. Also, don't know how to get channel_id given a channel name, have to look that up, never seen any docs on how to get that. Sorry if this is TMI.

**Comment by ORESoftware** [comment]
this should suffice - https://api.slack.com/methods/channels.list

but yeah, definitely a solid +1 for your docs to say channelId/channel_id instead of channel for methods that need id instead name

**Comment by brianleroux** [comment]
S'ok, ya their API could be improved. Always the way! :)

Here's how you get a list of channels (and their ids)

https://api.slack.com/methods/channels.list

**Comment by ORESoftware** [comment]
thanks yeah, I know you are trying to mirror their API 1:1 which makes sense, I will just refer to their docs more closely

**Comment by brianleroux** [comment]
👍👍👍

No worries happy to help and appreciate the perspective to make the lib better.

**Comment by ORESoftware** [comment]
:us:
