### ISSUE TITLE
Support for optional parameters in Web APIs.

### ISSUE THREAD

**Issue by gogeta95** [smallwins/slack#58]
Unable to find support or docs for optional parameters for any web API call. is this supported?

Basically I want to use `reactions.add` which is not possible without optional parameters.

https://api.slack.com/methods/reactions.add

> This method adds a reaction (emoji) to an item (file, file comment, channel message, group message, or direct message). One of file, `file_comment`, or the combination of `channel` and `timestamp` must be specified.

Thank you.

**Comment by brianleroux** [comment]
@gogeta95 dos for optional params are same as Slack API docs! 

```javascript
var slack = require('slack')
var token = 'xxx'
var name = ':heart:'
slack.reactions.add({token, name}, console.log) // only required
```

or full on

```javascript
var slack = require('slack')
var token = 'xxx'
var name = ':heart:'
var file = 'xxx'
var file_comment = 'xxx'
var channel = 'Cxxxxx'

slack.reactions.add({token, name, file, file_comment, channel}, console.log) // only required
```

HTH ! 👍
