### ISSUE TITLE
Catching rtm.client errors, how?

### ISSUE THREAD

**Issue by TheJimFactor** [smallwins/slack#59]
I'm currently using this slack module within an ionic 2 app and it is crashing whenever a user is kicked or joins a channel. Normal chat messages are being processed find. I've removed all code using this library except for 

```
this.bot = slack.rtm.client();
this.bot.listen({ token:this.token });
```
while debugging the application. How can  I catch this error and keep running?

```
TypeError: Cannot read property 'forEach' of undefined
    at WebSocket.message (rtm.client-browser.js:54)
    at WebSocket.n [as _onmessage] (polyfills.js:2)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (ng_zone.js:227)
    at t.invokeTask (polyfills.js:3)
    at e.runTask (polyfills.js:3)
    at WebSocket.invoke (polyfills.js:3)
```

**Comment by brianleroux** [comment]
Hey @TheJimFactor my guess is https://github.com/smallwins/slack/blob/master/src/rtm.client-browser.js#L18 is failing because https://github.com/smallwins/slack/blob/master/src/rtm.events.js file is missing?

**Comment by brianleroux** [comment]
@TheJimFactor 👋 anything else I can do to help?

**Comment by brianleroux** [comment]
Closing but want you to know if there's any issue pls reopen and lmk---here to help!
