### ISSUE TITLE
Add promise support

### ISSUE THREAD

**Issue by bmajz** [smallwins/slack#60]
Would love to have support for Promises rather than having to promisify manually every time we use the library. Recognize that there are issues with defaulting to a specific promise library, but this should be possible to work around by having the user specify a promise library if they wish to do so. Unfortunately, that would probably break the stateless nature of the API 👎 

Opening an issue to discuss the tradeoffs (already previously touched upon here):
[Issue 51](https://github.com/smallwins/slack/issues/51)

**Comment by brianleroux** [comment]
I dislike the `Promise` primitive but now that it has been ratified into the language I expect this sort of discussion to happen more often so this thread is a great opportunity to explore approaches. There's no One True Way™ to build asynchronous software and I can appreciate the syntactic aesthetic draw of Promises. 

My shortlist of problems:

- very easy to swallow errors (arguably same w errbacks)
- no stack traces even when you do get an Error
- performance is worse than pure errback functions
- has no symmetry with the Node runtime (arguably not with the browser runtime either)
- downstream consumers of this library would need the ability to override the promise choice or could experience divergent behavior from clobbering (this forces a configuration to use)

The error handling stuff is a very serious flaw. I can't stress enough how important it is to be able to quickly diagnose the locality of a problem when dealing with concurrent operations. Typically we spend more time debugging code than we do authoring. And in this light, by using Promises you are deliberately choosing a perceived aesthetic improvement while trading off performance and making your [code harder to analyze at runtime](http://joyent.com/blog/post-mortem-debugging-and-promises). 

The concrete problem to solve, if we choose to solve it, is how the configuration could be an opt-in so not everyone using the library is opted into its code. If it requires a configuration opt in then we are kind of back to the original problem of making the end consumer promisify. (I hear Bluebird is nice and makes it super easy to turn this library into them!)

My $0.02! 🍕

**Comment by lwhiteley** [comment]
as a work around for now if you really need promises

you can just used bluebird.promisify

http://bluebirdjs.com/docs/api/promise.promisify.html

**Comment by brianleroux** [comment]
closing for now---but looking at the new new new nodes w async/await and better error handling with a very careful eye. if they fix the line number issues we'll support!
