### ISSUE TITLE
help!! bot for welcome to user

### ISSUE THREAD

**Issue by thavoo** [smallwins/slack#65]
I try to make a bot that welcome a user who joined a channel as I get the variable user?

**Comment by brianleroux** [comment]
Totally possible -- recommend getting started here https://api.slack.com (you'll want to create an app using the Events API and setup a bot that is subscribed to the `channel_joined` event. (It is not "officially" supported but they do broadcast it to bots.) The value for the userID will be the in event payload.

Good luck!

**Comment by thavoo** [comment]
Thanks my friend
