### ISSUE TITLE
how can i create and delete channel in node?

### ISSUE THREAD

**Issue by csrgxtu** [smallwins/slack#66]
slack.channels.create({token, name}, (err, data) => { }) is for create, but what is for delete?

**Comment by brianleroux** [comment]
No method to delete but you can archive.

```
slack.channels.archive({token, channel}, (err, data) => { })
```

https://api.slack.com/methods/channels.archive

Youll need `channels:write` scope. 

https://api.slack.com/docs/oauth-scopes

HTH 🎸
