### ISSUE TITLE
Missing Scope

### ISSUE THREAD

**Issue by tloriato** [smallwins/slack#67]
Hello! Wanted to first say thank you about the lib and then head to the question!

I had created a bot for my team using these tools and they were working great! However, now I have to do a **search** on the channel and I'm stuck.

- **Missing Scope** is my _currently_ error
![image](https://cloud.githubusercontent.com/assets/11580564/24173121/9c01c956-0e69-11e7-8904-6a1f0670b7e7.png)

- - -
After reading a lot online here's what I did:

- I was using it as a custom integration, so I created an official Slack App now.
- I updated the token that I'm using.

- - -
How's the code?

- My **"header"**:

```
// Nightmare Stuff
var Nightmare = require("nightmare");

var night = false;
var nightmare = null;

const realMouse = require('nightmare-real-mouse');
realMouse(Nightmare);

// Misc.
var request = require("request");
var fileSystem = require("fs");

//Slack Stuff
var slack = require("slack");
var env = require("node-env-file");
var path = require("path");
var bot = slack.rtm.client();

// Load Environment Variables
env(path.join(__dirname, ".env"));


// Anti-Captcha
var anticaptcha = require('./anticaptcha')(process.env.ANTI_TOKEN);

// Grab the auth token
var token = process.env.SLACK_BOT_TOKEN;
```

- I **connect** using this:
```
var token = process.env.SLACK_BOT_TOKEN;

bot.listen({
  token
});
```
That was taken from **OAuth & Permissions** page from **App**

- After "listening" and validating what I want, **I'm calling search this way**:
`slack.search.messages({token, query: name}, (err, data) => {console.log(err)});`

- - -
Could you help me? I realize it's a broad issue, but I tried to provide all the relevant info's.

Thank you so much!

**Comment by brianleroux** [comment]
hmmmm! I suspect you do not have the right scope for that `SLACK_BOT_TOKEN` to use `search.messages`. looking at the [API docs](https://api.slack.com/apps/A0H8X1J5C/oauth) it appears you need to add `search:read` here:

<img width="540" alt="screen shot 2017-03-22 at 4 23 22 pm" src="https://cloud.githubusercontent.com/assets/990/24225103/ed28f0cc-0f1b-11e7-8ae7-26fb422f3890.png">

Closing for now but feel free to followup for help in this issue! 💟

**Comment by tloriato** [comment]
I do :(

![image](https://cloud.githubusercontent.com/assets/11580564/24225978/7325ff0a-0f42-11e7-85c7-7c257671c724.png)

It turns out that I won't be needing this, but I kinda think that I wanna know how this could work 😄

**Comment by lwhiteley** [comment]
i had this same issue. was an issue with this modules documentation.

if you are using the bot then you should be using the bot token and not the general oauth token

**Comment by brianleroux** [comment]
Hi @lwhiteley thx for the feedback. How can I make this module's documentation more clear? 

Appreciate any suggestions---I'm a bit blind to this being used to the weirdness of the the Slack platform take on oauth tokens. =)

**Comment by lwhiteley** [comment]
yea to me as well bot token and oauth token is a bit redundant since they both receive the same permissions. 

not sure why they separation.

but i think the examples in the readme just need to specify when to use which token more clearly

This is a mixed example using both the bot and web api

```js
const slack = require('slack')

let bot = slack.rtm.client()

let authToken = process.env.SLACK_TOKEN
let botToken = process.env.SLACK_BOT_TOKEN
// logs: ws, started, close, listen, etc... in addition to the RTM event handler methods 
console.log(Object.keys(bot))
 
// do something with the rtm.start payload 
bot.started(function(payload) {
//   console.log('payload from rtm.start', payload)
})
 
// respond to a user_typing message 
bot.message(function(msg) {
  const channel = 'general'
  const text = `msg was sent: ${msg.text}`
  slack.chat.postMessage({
      token: authToken, 
      channel, 
      text,
      mrkdwn: true,
      attachments: [
          {
              text: 'this is attachments as well'
          }
      ]
  }, 
  (err, data) => { 
      console.log(err, data)
  })
})

// start listening to the slack team associated to the token 
bot.listen({token:botToken})
```

As you can see above
`authToken` is being used for the web api call
`botToken` is being used for the bot listen

**Comment by brianleroux** [comment]
Ok, so that'll work but that might be _more_ misleading. Just got a response from the Slack team which I think is very clear (but pls verify this makes sense to you---and I'll add to the `readme.md`).

> When you install with `Add to Slack`, you get two kinds of tokens when asking for the `bot` scope. They are both access tokens. One of them is the "user" access token and represents the user who installed it and also is imbued with any oauth scopes you requested _besides_ `bot`. Then there's a "bot_user_token" which represents your bot user and a package of pre-determined permissions afforded to it.  Any other OAuth scopes requested in the installation process only apply to the user token, not to the bot token.

**Comment by iamtmrobinson** [comment]
Thanks @lwhiteley that was super useful. I was banging my head against a brick wall with a response of missing_scope thinking it was something I needed to provide as part of my request, but actually it was just that I was using the token rather than the bot token.
