### ISSUE TITLE
stdin stdout

### ISSUE THREAD

**Issue by danil-z** [smallwins/slack#68]
Hi folks,

I can't  access process.stdin process.stdout after bot starts listen.
I wonder how to make it?

for example this callback is never called:

```
process.stdin.pipe(require('split')()).on('data', processLine)

function processLine (line) {
  console.log(line + '!')
}

bot.listen({token})
```

**Comment by brianleroux** [comment]
Hey @danil-z ---can you describe what you're trying to do for me? (There's a few ways I can think of to achieve this depending on your use case.)

**Comment by danil-z** [comment]
nvm it was vscode issue. sorry for false alarm ;)

**Comment by brianleroux** [comment]
np! come by anytime; happy to help. 🍻
