### ISSUE TITLE
Catching disconnects and reconnecting listener

### ISSUE THREAD

**Issue by mastef** [smallwins/slack#70]
Hey there! So sometimes ( not regularly ) the client just stops listening while the node script is still running. On the local mac environment I can trigger this with a wifi disconnect or going into sleep mode. On servers it also seems to happen from time to time, although they should be pretty much online 24/7.

How to catch disconnects and then restart the client?

```js
var client = slack.rtm.client()

client.message(function(message) {
	// do something with message
});

client.listen(
	{token:sl.slacktoken}
);

// how to catch disconnects and reconnect client?
```

**Comment by statico** [comment]
FWIW, botkit had to address this problem too: https://github.com/howdyai/botkit/issues/261#issuecomment-258954201
