### ISSUE TITLE
slack.auth.revoke({}, (err, data) => { }) function not found

### ISSUE THREAD

**Issue by jli227** [smallwins/slack#71]
As of the npm module 8.3.0, the slack.auth.revoke function is not being supported.

When I log the module's functions to console, the auth object only contains the test object.
![image](https://cloud.githubusercontent.com/assets/13812345/25807161/b4b58c6e-33ba-11e7-8755-3708594448cd.png)

As of currently, I'm unauthenticating by removing all stored credentials in the database, but it'd be great to be able to unauthenticate the Slack integration when needed!

**Comment by brianleroux** [comment]
Good catch! Sorry about that! fixed in latest 💯
