### ISSUE TITLE
Simple code to get most recent message

### ISSUE THREAD

**Issue by pnoeric** [smallwins/slack#72]
Hey, I'm a bit of a beginner here. Is there any simple, sample code to help me learn to use this library? I'm build a bot with Beepboop and the Slapp framework (which uses this smallwins slack library), and I want to trying to fetch the most recent message in the current channel. So, when the user types /mybot lastmessage, it should run this code to use channel.history to pull the most recent:

```
slapp.message('lastmessage', ['mention', 'direct_message'], (msg) => {

  // grab the token and channel ID from the message that invoked this
  var token = msg.body.token;
  var channel = msg.body.event.channel;

  // want to use https://api.slack.com/methods/channels.history/test API call here
  ret = slack.channels.history({token, channel, 'count': 1}, (err, data) => { })

  // most recent message
  msg.say(`results ${JSON.stringify(ret)}`)
})
```

My code is failing on the `ret =` line... I'm not sure of the correct syntax to structure this. Would appreciate any guidance!

**Comment by pnoeric** [comment]
Nevermind. Figured it out ;-)

**Comment by brianleroux** [comment]
Glad to hear it---sorry I didn't get back to you sooner but don't hesitate to ping again. Often you can catch one of us in the dev4slack Slack if you need more real time help! 

http://dev4slack.xoxco.com/
