### ISSUE TITLE
slack.chat.update API

### ISSUE THREAD

**Issue by itsmejainh** [smallwins/slack#73]
Hi - 

I am the owner of a Slack team and have created a App and associated a bot with it. 

My requirement is to update every message posted by a user on a specified channel. To achieve this - I have specified permissions - **chat:write:user** along with few other permissions to the App and generated Access Tokens for Bot and App after installing App to team. 

Everything works fine when I post a message as it gets updated using slack.chat.update API. 

But - when a new user joins a channel and his messages are not being updated by the API and I get below error - **Error: cant_update_message**

Could someone please help me on this. 

thanks.

**Comment by itsmejainh** [comment]
I tried giving "Add to Slack" Application link of the new user and he gets a error message - "Uh oh, you need to be a Team Admin on ivp to install"

Is there a way to make Application available to all users in Team ?

Maybe I am missing something here. My requirement is to apply some formatting to every message users posts on slack channel. 

Please advise. thank you.

**Comment by brianleroux** [comment]
Sorry didn't see this one! Let me know if you still need help. 👍
