### ISSUE TITLE
How to obtain the token

### ISSUE THREAD

**Issue by jiayihu** [smallwins/slack#76]
I'm stuck in the basic process of obtaining a token from Slack API. I've read the docs for Slack APIs but I can only find mentions of Slack apps, which require an install from team admins. 

Is there any way to get a personal token, which authenticate a request as from myself?

**Comment by brianleroux** [comment]
Hey @jiayihu 
1. Go to https://api.slack.com 
2. Click on your app and then navigate to "OAuth & Permissions" (in sidebar)
3. Copy a token generated for testing on screen shown in the pic below

HTH!

<img width="638" alt="screen shot 2017-08-01 at 9 48 56 am" src="https://user-images.githubusercontent.com/990/28836660-abf42744-769e-11e7-867c-afe72d6955ad.png">

**Comment by jiayihu** [comment]
![schermata 2017-08-01 alle 18 57 47](https://user-images.githubusercontent.com/10067273/28836948-5984d31c-76eb-11e7-9b92-f2d51b571718.png)
As I said this method require an install and I don't have the privileges to do so

**Comment by brianleroux** [comment]
Ah, well, you could setup a testing Slack you control to get your bot going

**Comment by srl295** [comment]
In general, it's not clear how the variables map to the token types in https://api.slack.com/docs/token-types#verification

* `SLACK_BOT_TOKEN` = "Bot User Token"
* `SLACK_TOKEN` = ??  Verification token?

**Comment by brianleroux** [comment]
sorry about that @srl295 ---slack has been adding types like gangbusters this past year. used to only be one! `SLACK_BOT_TOKEN` is a [bot token](https://api.slack.com/docs/token-types#bot) and the `SLACK_TOKEN` is old/bad docs and should be removed. (You do not need it.)

My `.env` file looks like this:

```
SLACK_CLIENT_ID=xxx
SLACK_CLIENT_SECRET=xxx
SLACK_BOT_TOKEN=xoxp-xxx
```

**Comment by srl295** [comment]
Thanks!

**Comment by brianleroux** [comment]
np, updated teh docs a bit to hopefully be more clear. also don't hesitate to open an issue if you have more questions! I don't mind. 👊 💕
