### ISSUE TITLE
naming the bot?

### ISSUE THREAD

**Issue by matthewmueller** [smallwins/slack#9]
Apologies if I missed it somewhere in the docs, but seems like when you start a bot, it's given the name `bot` and a default thumbnail, but when I generated the token I set the name and thumbnail.

Is there a way to specify this override somewhere in the RTM client?

**Comment by brianleroux** [comment]
hey @matthewmueller you can override the bot name and thumb in https://api.slack.com/methods/chat.postMessage

(p easy to test out by using this modules repl)

**Comment by matthewmueller** [comment]
ahh there it is. thanks! the repl is a nice feature :-D

**Comment by brianleroux** [comment]
thx! just created a quickstart here too https://github.com/brianleroux/slack-example =)
