### ISSUE TITLE
When Building, I get a "Failed to minify the code" error

### ISSUE THREAD

**Issue by sshadmand** [smallwins/slack#90]
To reproduce:

Using `react-scripts build` after a `yarn add slack`

I get this error message:

```
Failed to minify the code from this file: 

 	./node_modules/slack/src/_bind.js:10 

Read more here: http://bit.ly/2tRViJ9
```
[The link](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify) says I need to open a ticket with the creator of the package.

**Comment by brianleroux** [comment]
Some quick thoughts on this https://twitter.com/brianleroux/status/923581596720013312

IDK there should be a workaround to write code (ES5) that runs in a browser without a transpile step.

**Comment by sshadmand** [comment]
Thanks for the quick reply @brianleroux. Will keep churning through the interwebs, and monkeying the code, to see if a solutions presents itself. If anything comes to mind I'm all ears.

**Comment by brianleroux** [comment]
Yeah I'm going to give myself a timeblock to see if I can find a way to keep you moving forward. It's really ridiculous browser tested code isn't compatible with this thing. [0] 

You could make a standalone build [1] and just include the script.  (You'll need to modify that `pkg` command to export `slack` as a global.)

[0] https://github.com/smallwins/slack/blob/master/package.json#L15
[1] https://github.com/smallwins/slack/blob/master/package.json#L17

**Comment by sshadmand** [comment]
@brianleroux I used the 'standalone' to generate a min file for the time being, but got an error when adding it to the page:

```
slack.node.min.js:1 Uncaught Error: Cannot find module 'http'
    at s (slack.node.min.js:1)
    at slack.node.min.js:1
    at Object.1.http (slack.node.min.js:1)
    at s (slack.node.min.js:1)
    at slack.node.min.js:1
    at Object.3../_read (slack.node.min.js:61)
    at s (slack.node.min.js:1)
    at slack.node.min.js:1
    at Object.5../_origin (slack.node.min.js:73)
    at s (slack.node.min.js:1)
```

**Comment by brianleroux** [comment]
Ah yes, `standalone` is for building standalone node builds. You want `pkg` (but again you'll need to modify that script to export `slack` as a global.

**Comment by sshadmand** [comment]
@brianleroux I got the global version of the package implementation to work, so thanks for that tip. Looking forward to getting back into the more standard `import` system. 

All that being said, I am super grateful that you put this package together! It's real easy to use. 

I'll buy you a beer if you in SF 😄 🍺

**Comment by brianleroux** [comment]
Nice! Great. Yes I am in SF and love 🍺 ! Ping me on email b@brian.io 👍 

Also thx @gaearon for create-react-app responsiveness 🙏
