### ISSUE TITLE
generate typescript declarations from openapi definitions

### ISSUE THREAD

**Issue by danprince** [smallwins/slack#94]
The current set of typescript declarations have to include an index signature to cover the optional parameters.

https://github.com/smallwins/slack/blob/88931653972942b7738dbeef0308161fe803ed96/slack.d.ts#L52-L62

Looks like we currently scrape these params, then filter them out.

https://github.com/smallwins/slack/blob/88931653972942b7738dbeef0308161fe803ed96/scripts/generate-api-json#L44-L51

Could instead generate an `api.json` that looked like:

```json
{
  "name": {
    "required": ["token"],
    "optional": ["cursor", "limit"]
  }
}
```

**Comment by brianleroux** [comment]
yep! there's also a rumored swagger defn api "coming soon" so we'll be able to get much more involved ---only caveat I'd ask that we strip those optionals after the typedefs are generated to (again) keep the payload as small as possible! 🙏

**Comment by danprince** [comment]
Ah sweet. Swagger defs would be good. I'll have a think about how we might do it in the meantime, don't want to make the generation step too complex, just for the sake of TS users.

**Comment by danprince** [comment]
Well, that was quick.

https://medium.com/slack-developer-blog/standard-practice-slack-web-openapi-spec-daaad18c7f8

**Comment by brianleroux** [comment]
oh snap! will be interesting to see the delta for our generator scripts (cheers for the release @episod 💯)

**Comment by brianleroux** [comment]
think we can close this @danprince ?

**Comment by danprince** [comment]
I'm still hoping to get this done (currently rock climbing in Thailand though...) so feel free to close it for now and I'll open a PR at some point when I'm back on track.

**Comment by brianleroux** [comment]
Sounds like you're totally on track imo! 💪
