### ISSUE TITLE
npm run pkg - Failed to compile.

### ISSUE THREAD

**Issue by arod2634** [smallwins/slack#97]
I get the following error after performing 'npm run pkg' and manually including the compiled JS into my app.

`Failed to compile.

./src/helpers/slack.min.js
Line 1: 'define' is not defined no-undef
Line 1: 'define' is not defined no-undef
Line 1: Unexpected use of 'self' no-restricted-globals
Line 1: Unexpected use of 'self' no-restricted-globals

Search for the keywords to learn more about each error.`

<img width="480" alt="screen shot 2017-11-19 at 5 39 16 pm" src="https://user-images.githubusercontent.com/632906/32997121-39b9a320-cd51-11e7-99c5-5c45d40f8ff0.png">

**Comment by arod2634** [comment]
This is related to #96

**Comment by brianleroux** [comment]
super close! @arod2634 can you cut me a repo that reproduces the issue to play with?

**Comment by arod2634** [comment]
https://github.com/arod2634/create-react-app-slack-test/invitations

**Comment by arod2634** [comment]
https://github.com/arod2634/create-react-app-slack-test

**Comment by brianleroux** [comment]
[update] This is an issue with the React tooling. (It def is not a bug with our code having browser compat.) Opened an issue with them here https://github.com/facebookincubator/create-react-app/issues/3479

**Comment by brianleroux** [comment]
Good new @arod2634 / all you need to do to fix this is to delete slack.min.js and then use `var slack = require('slack')` and make sure that you `npm i slack --save` into your node_modules so that create-react-app can find it!
