### ISSUE TITLE
Support request retry

### ISSUE THREAD

**Issue by CharlieHess** [smallwins/slack#99]
Consider wrapping requests in something like [`node-retry`](https://github.com/tim-kos/node-retry) for more reliability in unstable network conditions. For clients in production the alternative is to wrap every `slack.api` call in something similar, so it might make sense to plug it in here.

**Comment by brianleroux** [comment]
I have never seen a network request fail in the manner described in two years of production use—are you getting 500s from Slack or?

**Comment by CharlieHess** [comment]
No, not 500s. 😝 Try disconnecting your wifi intermittently during a request, changing wifi networks, switching to a network with active throttling enabled or 2G.

**Comment by brianleroux** [comment]
Ok, I like that feature but do think its an app level concern not something for this library should do. (Seems like a clientside concern given the examples.)

**Comment by CharlieHess** [comment]
That's a fair response. 👍
